{{- if .Values.global.metrics.prometheus.enabled }}
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-prometheus
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
{{- end }}
{{- end }}
