{{- if .Values.global.metrics.prometheus.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-prometheus
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
{{- end }}
