<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.edu_sharing</groupId>
    <artifactId>edu_sharing-projects-community-deploy</artifactId>
    <version>git</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>edu_sharing-projects-community-deploy-docker</artifactId>
  <packaging>pom</packaging>
  <name>edu_sharing-projects-community-deploy-docker</name>
  <properties>
    <docker.edu_sharing.community.common.minideb.name>
      edu_sharing-community-common-docker-minideb
    </docker.edu_sharing.community.common.minideb.name>
    <docker.edu_sharing.community.common.minideb.tag>
      12.0.1
    </docker.edu_sharing.community.common.minideb.tag>
    <docker.edu_sharing.community.common.redis.exporter.name>
      edu_sharing-community-common-docker-redis-export
    </docker.edu_sharing.community.common.redis.exporter.name>
    <docker.edu_sharing.community.common.redis.exporter.tag>
      1.74.0
    </docker.edu_sharing.community.common.redis.exporter.tag>
    <docker.edu_sharing.community.common.redis-cluster.name>
      edu_sharing-community-common-docker-redis-cluster
    </docker.edu_sharing.community.common.redis-cluster.name>
    <docker.edu_sharing.community.common.redis-cluster.tag>
      8.0.3
    </docker.edu_sharing.community.common.redis-cluster.tag>
    <docker.edu_sharing.community.common.mongodb.name>
      edu_sharing-community-common-docker-mongodb
    </docker.edu_sharing.community.common.mongodb.name>
    <docker.edu_sharing.community.common.mongodb.tag>
      7.0.15
    </docker.edu_sharing.community.common.mongodb.tag>
    <docker.edu_sharing.community.common.mongodb>
      ${docker.registry}/${docker.common}/${docker.edu_sharing.community.common.mongodb.name}:${docker.edu_sharing.community.common.mongodb.tag}
    </docker.edu_sharing.community.common.mongodb>
    <docker.edu_sharing.community.common.onyx.name>
      edu_sharing-community-common-docker-onyx
    </docker.edu_sharing.community.common.onyx.name>
    <docker.edu_sharing.community.common.onyx.tag>
      2025.05.1-0
    </docker.edu_sharing.community.common.onyx.tag>
    <docker.edu_sharing.community.common.onyx>
      ${docker.registry}/${docker.common}/${docker.edu_sharing.community.common.onyx.name}:${docker.edu_sharing.community.common.onyx.tag}
    </docker.edu_sharing.community.common.onyx>
    <helm.kube.version>&gt;= 1.20.0-0</helm.kube.version>
    <helm.version>3.14.2</helm.version>
  </properties>
  <profiles>
    <profile>
      <id>deploy.deploy.docker.customer</id>
      <activation>
        <activeByDefault>false</activeByDefault>
        <file>
          <exists>customer/pom.xml</exists>
        </file>
      </activation>
      <modules>
        <module>customer</module>
      </modules>
    </profile>
  </profiles>
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>io.kokuwa.maven</groupId>
          <artifactId>helm-maven-plugin</artifactId>
          <configuration>
            <helmVersion>${helm.version}</helmVersion>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>3.1.0</version>
        <executions>
          <execution>
            <phase>validate</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <target>
                <echo file=".composeProjectName">${project.version.base}</echo>
                <replaceregexp byline="true" file=".composeProjectName" match="-SNAPSHOT" replace=""/>
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <modules>
    <module>compose</module>
    <module>helm</module>
  </modules>
</project>
