apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edusharing_rendering_service.name" . }}-env
  labels: {{ include "edusharing_rendering_service.labels" . | nindent 4 }}
type: Opaque
data:
  REPOSITORY_SERVICE_ADMIN_PASS: {{ .Values.config.repository.password | b64enc | quote }}
  SERVICES_RENDERING_DATABASE_USER: {{ .Values.config.database.username | b64enc | quote }}
  SERVICES_RENDERING_DATABASE_PASS: {{ .Values.config.database.password | b64enc | quote }}
