version: '3.7'

services:

  cache:
    image: "${docker.repository}/${docker.prefix}-deploy-docker-build-redis:${docker.tag}"
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${CACHE_PORT:-7000}:6379"

  profiler:
    image: "${docker.repository}/${docker.prefix}-deploy-docker-build-profiler:${docker.tag}"
    container_name: "profiler_${COMPOSE_PROJECT_NAME}"
    pid: "host"
    userns_mode: "host"
    privileged: true
    volumes:
      - "profiler:/opt/profiler"

volumes:
  profiler:
