version: '3.7'

services:

  repository-service:
    environment:
      CACHE_HOST: ""
      CACHE_PORT: ""
    volumes:
      - "${GIT_ROOT}/deploy/repository/Backend/alfresco/module/target/edu_sharing-projects-community-repository-backend-alfresco-module-${org.edu_sharing:edu_sharing-projects-community-repository-backend-alfresco-module:amp.version}.amp:/opt/alfresco/amps/alfresco/3/edu_sharing-projects-community-repository-backend-alfresco-module-${org.edu_sharing:edu_sharing-projects-community-repository-backend-alfresco-module:amp.version}.amp"
      - "${GIT_ROOT}/deploy/repository/Backend/services/core/target/edu_sharing-projects-community-repository-backend-services-core-${org.edu_sharing:edu_sharing-projects-community-repository-backend-services-core:jar.version}.jar:/opt/alfresco/tomcat/webapps/edu-sharing/WEB-INF/lib/edu_sharing-projects-community-repository-backend-services-core-${org.edu_sharing:edu_sharing-projects-community-repository-backend-services-core:jar.version}.jar"
      - "${GIT_ROOT}/deploy/repository/config/defaults/target/classes:/opt/alfresco/tomcat/shared/classes/config/defaults"
