{{- if .Values.global.prometheus.enabled }}
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" -}}
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ include "edusharing.name" . }}
  labels: {{ include "edusharing.labels" . | nindent 4 }}
spec:
  additionalScrapeConfigs:
    name: {{ include "edusharing.name" . }}-prometheus
    key:  additionalScrapeConfigs
  retention: {{ .Values.global.prometheus.retention }}
  scrapeInterval: {{ .Values.global.prometheus.scrapeInterval }}
  scrapeTimeout: {{ .Values.global.prometheus.scrapeTimeout }}
  serviceAccountName: {{ include "edusharing.name" . }}-prometheus
  serviceMonitorSelector: {}
{{- end }}
{{- end }}
