{{- if .Values.global.prometheus.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edusharing.name" . }}-prometheus
  labels: {{ include "edusharing.labels" . | nindent 4 }}
type: Opaque
stringData:
  additionalScrapeConfigs: |
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
      - namespaces:
          names:
          - {{ .Release.Namespace }}
        role: pod
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_path
        target_label: __metrics_path__
      - action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        source_labels:
        - __address__
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod_name
      - action: drop
        regex: Pending|Succeeded|Failed
        source_labels:
        - __meta_kubernetes_pod_phase
{{- end }}
