{{- if .Values.config.saml.enabled }}
{{- with .Values.config.saml.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_repository_service.name" $ }}-saml-file
  labels: {{ include "edusharing_repository_service.labels.app" $ | nindent 4 }}
data:
  security: |-
{{ . | indent 4 }}
{{- end }}
{{- end }}
