apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_repository_service.name" . }}-file
  labels: {{ include "edusharing_repository_service.labels.app" . | nindent 4 }}
data:
{{- with .Values.config.override.config.application.client }}
  config-application-client: |
    {{ . | nindent 4 }}
{{- end }}
{{- with .Values.config.override.config.application.server }}
  config-application-server: |
    {{ . | nindent 4 }}
{{- end }}
{{- with .Values.config.override.logging.application }}
  logging-application: |
    {{ . | nindent 4 }}
{{- end }}
{{- with .Values.config.override.logging.server }}
  logging-server: |
    {{ . | nindent 4 }}
{{- end }}