{{- if .Values.global.cluster.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "edusharing_repository_service.name" . }}
  labels: {{ include "edusharing_repository_service.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ if .Values.config.cluster.enabled }}{{ .Values.config.cluster.backup.count }}{{ else }}0{{ end }}
  selector:
    matchLabels: {{ include "edusharing_repository_service.labels.instance" . | nindent 6 }}
{{- end }}