{{- if .Values.global.cluster.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "edusharing_repository_service.name" . }}
  labels: {{ include "edusharing_repository_service.labels.app" . | nindent 4 }}
spec:
  {{- if .Values.config.cluster.enabled }}
  maxUnavailable: {{ .Values.config.cluster.backup.count }}
  {{- else }}
  minAvailable: 1
  {{- end }}
  selector:
    matchLabels: {{ include "edusharing_repository_service.labels.app" . | nindent 6 }}
{{- end }}