apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edusharing_repository_service.name" . }}-env
  labels: {{ include "edusharing_repository_service.labels.app" . | nindent 4 }}
type: Opaque
data:
  REPOSITORY_DATABASE_USER: {{ .Values.config.database.username | b64enc | quote }}
  REPOSITORY_DATABASE_PASS: {{ default .Values.global.password .Values.config.database.password | b64enc | quote }}
  {{- if .Values.config.mongo.enabled }}
  REPOSITORY_MONGO_CONNECTION_STRING: {{ (printf "mongodb://%s:%s@%s-0:%d,%s-1:%d,%s-2:%d/%s" .Values.config.mongo.username (default .Values.global.password .Values.config.mongo.password) .Values.config.mongo.host (.Values.config.mongo.port | int) .Values.config.mongo.host (.Values.config.mongo.port | int) .Values.config.mongo.host (.Values.config.mongo.port | int) .Values.config.mongo.database) | b64enc | quote }}
  {{- end }}
  REPOSITORY_SERVICE_ADMIN_PASS: {{ default .Values.global.password .Values.config.admin.password | b64enc | quote }}
  REPOSITORY_SERVICE_GUEST_USER: {{ .Values.config.guest.username | b64enc | quote }}
  REPOSITORY_SERVICE_GUEST_PASS: {{ .Values.config.guest.password | b64enc | quote }}
  REPOSITORY_SERVICE_MAIL_SERVER_SMTP_USERNAME: {{ .Values.config.mail.server.smtp.username | b64enc | quote }}
  REPOSITORY_SERVICE_MAIL_SERVER_SMTP_PASSWORD: {{ .Values.config.mail.server.smtp.password | b64enc | quote }}
