apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edusharing_repository_service.name" . }}-env
  labels: {{ include "edusharing_repository_service.labels.app" . | nindent 4 }}
type: Opaque
data:
  REPOSITORY_DATABASE_USER: {{ .Values.config.database.username | b64enc | quote }}
  REPOSITORY_DATABASE_PASS: {{ .Values.config.database.password | b64enc | quote }}
  REPOSITORY_SERVICE_ADMIN_PASS: {{ .Values.config.admin.password | b64enc | quote }}
  REPOSITORY_SERVICE_GUEST_USER: {{ .Values.config.guest.username | b64enc | quote }}
  REPOSITORY_SERVICE_GUEST_PASS: {{ .Values.config.guest.password | b64enc | quote }}
  REPOSITORY_SERVICE_MAIL_SERVER_SMTP_USERNAME: {{ .Values.config.mail.server.smtp.username | b64enc | quote }}
  REPOSITORY_SERVICE_MAIL_SERVER_SMTP_PASSWORD: {{ .Values.config.mail.server.smtp.password | b64enc | quote }}
