apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_repository_service.name" . }}
  labels: {{ include "edusharing_repository_service.labels.app" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{ include "edusharing_repository_service.labels.app" . | nindent 4 }}
  ports:
  - name: http-api-external
    port: {{ .Values.service.port.api.external }}
    targetPort: api-{{ if .Values.proxy.enabled }}proxy{{ else }}external{{ end }}
  - name: http-api-internal
    port: {{ .Values.service.port.api.internal }}
    targetPort: api-internal
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_repository_service.name" . }}-headless
  labels: {{ include "edusharing_repository_service.labels.app" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector: {{ include "edusharing_repository_service.labels.app" . | nindent 4 }}
  ports:
  - name: http-api-external
    port: {{ .Values.service.port.api.external }}
  - name: http-api-internal
    port: {{ .Values.service.port.api.internal }}
  - name: tcp-gossip
    port: {{ .Values.service.port.gossip }}
{{- if .Values.global.metrics.servicemonitor.enabled }}
{{- if .Values.config.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_repository_service.name" . }}-metrics-api
  labels: {{ include "edusharing_repository_service.labels.app" . | nindent 4 }}
    app.kubernetes.io/component: "metrics-api"
spec:
  type: ClusterIP
  selector: {{ include "edusharing_repository_service.labels.app" . | nindent 4 }}
  ports:
    - name: http-metrics-api
      port: {{ .Values.service.port.metrics.api }}
      targetPort: metrics-api
{{- end }}
{{- if .Values.sidecar.proxyMetrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_repository_service.name" . }}-metrics-proxy
  labels: {{ include "edusharing_repository_service.labels.app" . | nindent 4 }}
    app.kubernetes.io/component: "metrics-proxy"
spec:
  type: ClusterIP
  selector: {{ include "edusharing_repository_service.labels.app" . | nindent 4 }}
  ports:
    - name: http-metrics-proxy
      port: {{ .Values.service.port.metrics.proxy }}
      targetPort: metrics-proxy
{{- end }}
{{- end }}