apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "edusharing_repository_service.name" . }}
  labels: {{ include "edusharing_repository_service.labels.app" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "edusharing_repository_service.labels.app" . | nindent 6 }}
  serviceName: {{ include "edusharing_repository_service.name" . }}-headless
  template:
    metadata:
      name: {{ include "edusharing_repository_service.name" . }}
      labels: {{ include "edusharing_repository_service.labels.app" . | nindent 8 }}
      annotations:
        checksum/configmap-env: {{ include (print .Template.BasePath "/configmap-env.yaml") . | sha256sum | trunc 63 }}
        checksum/configmap-file: {{ include (print .Template.BasePath "/configmap-file.yaml") . | sha256sum | trunc 63 }}
        {{- if .Values.config.saml.enabled }}
        {{- if .Values.config.saml.config }}
        checksum/configmap-saml-file: {{ include (print .Template.BasePath "/configmap-saml-file.yaml") . | sha256sum | trunc 63 }}
        {{- end }}
        {{- if .Values.config.saml.files }}
        checksum/configmap-saml-files: {{ include (print .Template.BasePath "/configmap-saml-files.yaml") . | sha256sum | trunc 63 }}
        {{- end }}
        {{- end }}
        checksum/secret-env: {{ include (print .Template.BasePath "/secret-env.yaml") . | sha256sum | trunc 63 }}
        {{- if not .Values.global.metrics.servicemonitor.enabled }}
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
        prometheus.io/scrape: {{ .Values.config.metrics | quote }}
        {{- end }}
        sidecar.istio.io/inject: {{ .Values.global.cluster.istio.enabled | quote }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
      {{- if (default .Values.global.cluster.storage.share.permission .Values.persistence.share.permission) }}
      - name: {{ include "edusharing_repository_service.name" . }}-init-permission
        image: {{ include "edusharing_repository_service.image" . }}{{ .Values.image.prefix }}-deploy-docker-build-minideb:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        command:
        - "/bin/bash"
        - "-ec"
        - |
          if [[ ! "$(ls -A /usr/local/tomcat/shared/classes/config/cluster)" ]]; then
            chown -R {{ .Values.podSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }} /usr/local/tomcat/shared/classes/config/cluster
          fi
          if [[ ! "$(ls -A /usr/local/tomcat/shared/classes/config/node)" ]]; then
            chown -R {{ .Values.podSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }} /usr/local/tomcat/shared/classes/config/node
          fi
          if [[ ! "$(ls -A /opt/alfresco/alf_data)" ]]; then
            chown -R {{ .Values.podSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }} /opt/alfresco/alf_data
          fi
        volumeMounts:
        - name: data
          mountPath: /usr/local/tomcat/shared/classes/config/node
        - name: share-config
          mountPath: /usr/local/tomcat/shared/classes/config/cluster
        - name: share-data
          mountPath: /opt/alfresco/alf_data
        {{- with .Values.init.permission.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.init.permission.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      containers:
      - name: {{ include "edusharing_repository_service.name" . }}-server
        image: {{ include "edusharing_repository_service.image" . }}{{ .Values.image.prefix }}-deploy-docker-repository-build-service:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        {{- if default .Values.global.debug .Values.debug }}
        args: [ "catalina.sh", "jpda", "run" ]
        {{- end }}
        {{- $patroni := merge .Values.config.database.patroni .Values.global.patroni }}
        {{- if $patroni.enabled }}
        env:
          - name: REPOSITORY_DATABASE_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.config.database.username }}.{{ $patroni.name }}.{{ $patroni.secrets }}
                key: password
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "edusharing_repository_service.name" . }}-env
        - secretRef:
            name: {{ include "edusharing_repository_service.name" . }}-env
        ports:
        - name: api-internal
          containerPort: 8080
        - name: api-external
          containerPort: 8081
        - name: gossip
          containerPort: 5701
        {{- if .Values.config.metrics }}
        - name: metrics
          containerPort: 9090
        {{- end }}
        {{- if default .Values.global.debug .Values.debug }}
        - name: jpda
          containerPort: 5005
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: /usr/local/tomcat/shared/classes/config/node
        - name: share-config
          mountPath: /usr/local/tomcat/shared/classes/config/cluster
        - name: share-data
          mountPath: /opt/alfresco/alf_data
        {{- with .Values.config.override.config.application.client }}
        - name: file
          mountPath: /usr/local/tomcat/shared/classes/config/defaults/client.config.xml
          subPath: config-application-client
        {{- end }}
        {{- with .Values.config.override.config.application.server }}
        - name: file
          mountPath: /usr/local/tomcat/shared/classes/config/cluster/edu-sharing.override.conf
          subPath: config-application-server
        {{- end }}
        {{- with .Values.config.override.logging.application }}
        - name: file
          mountPath: /usr/local/tomcat/webapps/alfresco/WEB-INF/classes/log4j2.xml
          subPath: logging-application
        {{- end }}
        {{- with .Values.config.override.logging.server }}
        - name: file
          mountPath: /usr/local/tomcat/conf/logging.properties
          subPath: logging-server
        {{- end }}
        {{- if .Values.config.saml.enabled }}
        {{- with .Values.config.saml.config }}
        - name: saml-file
          mountPath: /usr/local/tomcat/webapps/edu-sharing/WEB-INF/securityContext.xml
          subPath: security
        {{- end }}
        {{- with .Values.config.saml.files }}
        - name: saml-files
          mountPath: /usr/local/tomcat/webapps/edu-sharing/WEB-INF/classes/saml
        {{- end }}
        {{- end }}
        {{- with .Values.startupProbe }}
        startupProbe:
          httpGet:
            path: /edu-sharing/rest/_about/status/SERVICE?timeoutSeconds={{ .timeoutSeconds }}
            httpHeaders:
              - name: Accept
                value: application/json
            port: api-internal
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          tcpSocket:
            port: api-internal
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          httpGet:
            path: /edu-sharing/rest/_about/status/SERVICE?timeoutSeconds={{ .timeoutSeconds }}
            httpHeaders:
            - name: Accept
              value: application/json
            port: api-internal
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{ if not .Values.config.transform.server.enabled }}
      - name: {{ include "edusharing_repository_service.name" . }}-transform
        image: {{ include "edusharing_repository_service.image" . }}{{ .Values.image.prefix }}-deploy-docker-repository-build-transform:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "edusharing_repository_service.name" . }}-env
        ports:
        - name: api
          containerPort: 8100
        {{- with .Values.sidecar.transform.startupProbe }}
        startupProbe:
          exec:
            command:
              - "/bin/bash"
              - "-ec"
              - |
                unoconv -n -c 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ComponentContext' --stdout -f html /etc/hostname >/dev/null
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.sidecar.transform.livenessProbe }}
        livenessProbe:
          exec:
            command:
            - "/bin/bash"
            - "-ec"
            - |
              unoconv -n -c 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ComponentContext' --stdout -f html /etc/hostname >/dev/null
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: 1
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.sidecar.transform.readinessProbe }}
        readinessProbe:
          exec:
            command:
            - "/bin/bash"
            - "-ec"
            - |
              unoconv -n -c 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ComponentContext' --stdout -f html /etc/hostname >/dev/null
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.sidecar.transform.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.sidecar.transform.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{ with .Values.terminationGracePeriod }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- if or .Values.nodeAffinity .Values.podAntiAffinity }}
      affinity:
        {{- with .Values.nodeAffinity }}
        nodeAffinity: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.podAntiAffinity }}
        podAntiAffinity:
          {{- if eq .Values.podAntiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels: {{ include "edusharing_repository_service.labels.app" . | nindent 16 }}
          {{- else if eq .Values.podAntiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels: {{ include "edusharing_repository_service.labels.app" . | nindent 18 }}
          {{- end }}
        {{- end }}
      {{- end }}
      volumes:
      - name: share-config
        persistentVolumeClaim:
          claimName: {{ include "edusharing_repository_service.pvc.share.config" . }}
      - name: share-data
        persistentVolumeClaim:
          claimName: {{ include "edusharing_repository_service.pvc.share.data" . }}
      - name: file
        configMap:
          name: {{ include "edusharing_repository_service.name" . }}-file
      {{- if .Values.config.saml.enabled }}
      {{- with .Values.config.saml.config }}
      - name: saml-file
        configMap:
          name: {{ include "edusharing_repository_service.name" $ }}-saml-file
      {{- end }}
      {{- with .Values.config.saml.files }}
      - name: saml-files
        configMap:
          name: {{ include "edusharing_repository_service.name" $ }}-saml-files
      {{- end }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels: {{ include "edusharing_repository_service.labels.app" . | nindent 8 }}
    spec: {{ merge .Values.persistence.data.config.spec .Values.global.cluster.storage.data.spec | toYaml | nindent 6 }}