---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_rediscluster.name" . }}
  labels: {{ include "edusharing_rediscluster.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{ include "edusharing_rediscluster.labels.instance" . | nindent 4 }}
  ports:
  - name: tcp-api
    port: {{ .Values.service.port.api }}
    targetPort: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_rediscluster.name" . }}-headless
  labels: {{ include "edusharing_rediscluster.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector: {{ include "edusharing_rediscluster.labels.instance" . | nindent 4 }}
  ports:
  - name: tcp-api
    port: {{ .Values.service.port.api }}
  - name: tcp-gossip
    port: {{ .Values.service.port.gossip }}
