{{- if not .Values.global.patroni.enabled }}
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
{{- if .Values.global.metrics.servicemonitor.enabled }}
{{- if .Values.sidecar.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "edusharing_postgresql.name" . }}
  labels: {{ include "edusharing_postgresql.labels.app" . | nindent 4 }}
    app.kubernetes.io/component: "metrics"
spec:
  endpoints:
  - path: "/metrics"
    port: http-metrics
    interval: {{ .Values.global.metrics.scrape.interval }}
    scrapeTimeout: {{ .Values.global.metrics.scrape.timeout }}
    {{- with .Values.sidecar.metrics.relabelings }}
    metricRelabelings: {{ toYaml . | nindent 6 }}
    {{- end }}
  selector:
    matchLabels: {{ include "edusharing_postgresql.labels.app" . | nindent 6 }}
      app.kubernetes.io/component: "metrics"
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}