apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_repository_search_solr4.name" . }}-env
  labels: {{ include "edusharing_repository_search_solr4.labels.app" . | nindent 4 }}
data:
  ALLOW_EMPTY_PASSWORD: "yes"
  CATALINA_OPTS: >-
    {{- with .Values.config.jvm.ram.minPercentage }}
    -XX:InitialRAMPercentage={{ . }}
    {{- end }}
    {{- with .Values.config.jvm.ram.maxPercentage }}
    -XX:MaxRAMPercentage={{ . }}
    {{- end }}    
    -Dcom.sun.management.jmxremote
    -Dcom.sun.management.jmxremote.authenticate=false
    -Dcom.sun.management.jmxremote.port=7199
    -Dcom.sun.management.jmxremote.ssl=false
    {{- if .Values.config.metrics.enabled }}
    -javaagent:/opt/alfresco/tomcat/agent/jmx_prometheus_javaagent.jar=9090:/opt/alfresco/tomcat/agent/jmx-exporter-config.yaml
    {{- end }}
  JPDA_ADDRESS: "0.0.0.0:5005"
  REPOSITORY_SEARCH_SOLR4_HOST: {{ include "edusharing_repository_search_solr4.name" . | quote }}
  REPOSITORY_SEARCH_SOLR4_PORT: {{ .Values.service.port.api | quote }}
  REPOSITORY_SERVICE_HOST: {{ .Values.config.repository.host | quote }}
  REPOSITORY_SERVICE_PORT: {{ .Values.config.repository.port | quote }}
  TOMCAT_INSTALL_DEFAULT_WEBAPPS: "no"