apiVersion: v2

name: ${helm.prefix}
description: ${helm.prefix}

icon: ${helm.chart.icon}

version: ${helm.chart.version}
appVersion: ${docker.tag}
kubeVersion: "${helm.kube.version}"

dependencies:

  - name: edu_sharing-community-common-lib
    repository: ${helm.deploy.url}
    version: 1.x.x

  - name: edu_sharing-community-common-rediscluster
    repository: ${helm.deploy.url}
    version: 1.x.x
    alias: edusharing_rediscluster
    condition: edusharing_rediscluster.enabled

  - name: ${helm.prefix}-repository
    version: ${helm.chart.version}
    alias: edusharing_repository
    condition: edusharing_repository.enabled

  - name: edu_sharing-community-services-rendering
    ${helm.edusharing_services_rendering.line2}
    alias: edusharing_services_rendering
    condition: edusharing_services_rendering.enabled
