version: '3.7'

services:

  repository-database:
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_DATABASE_PORT:-8000}:5432"

  repository-mailcatcher:
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_MAILCATCHER_PORT_HTTP:-8025}:1080"

  repository-search-solr4:
    command: ["catalina.sh", "jpda", "run"]
    environment:
      JPDA_ADDRESS: "0.0.0.0:5005"
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_SEARCH_SOLR4_PORT_HTTP:-8200}:8080"
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_SEARCH_SOLR4_PORT_JPDA:-8201}:5005"

  repository-service:
    command: ["catalina.sh", "jpda", "run"]
    environment:
      JPDA_ADDRESS: "0.0.0.0:5005"
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_SERVICE_PORT_JPDA:-8101}:5005"
