version: '3.7'

services:

  repository-database:
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_DATABASE_PORT:-8000}:5432"

  repository-mailcatcher:
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_MAILCATCHER_PORT_HTTP:-8025}:1080"

  repository-search-solr4:
    environment:
      CATALINA_OPTS: >-
        -Xms${REPOSITORY_SEARCH_SOLR4_JAVA_XMS:-512m}
        -Xmx${REPOSITORY_SEARCH_SOLR4_JAVA_XMX:-512m}
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.port=7199
        -Dcom.sun.management.jmxremote.ssl=false
        -javaagent:/opt/alfresco/tomcat/agent/jmx_prometheus_javaagent.jar=9090:/opt/alfresco/tomcat/agent/jmx-exporter-config.yaml
        -agentlib:jdwp=transport=dt_socket,address=0.0.0.0:5005,server=y,suspend=n
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_SEARCH_SOLR4_PORT_HTTP:-8200}:8080"
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_SEARCH_SOLR4_PORT_JPDA:-8201}:5005"

  repository-service:
    environment:
      CATALINA_OPTS: >-
        -Xms${REPOSITORY_SERVICE_JAVA_XMS:-2g}
        -Xmx${REPOSITORY_SERVICE_JAVA_XMX:-4g}
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.port=7199
        -Dcom.sun.management.jmxremote.ssl=false
        -javaagent:/opt/alfresco/tomcat/agent/jmx_prometheus_javaagent.jar=9090:/opt/alfresco/tomcat/agent/jmx-exporter-config.yaml
        -agentlib:jdwp=transport=dt_socket,address=0.0.0.0:5005,server=y,suspend=n
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_SERVICE_PORT_JPDA:-8101}:5005"
